# Generated by Django 4.0.2 on 2022-02-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('ver_code', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('cpassword', models.CharField(max_length=20)),
                ('invite_code', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=30, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('rechage', models.IntegerField(default=0)),
            ],
        ),
    ]
